name: Revaulting
version: "${version}"
main: moe.minacle.minecraft.plugins.revaulting.Plugin
description: |
  Remove the one-time limit of Vaults and Ominous Vaults.
authors:
  - Minacle
website: https://modrinth.com/plugin/revaulting
api-version: "1.21"
